"""Add station management metadata

Revision ID: 0d91801a96b7
Revises: af0486fa4792
Create Date: 2026-06-27 20:32:27.675633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d91801a96b7'
down_revision = 'af0486fa4792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'supported_connectors',
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ))
        batch_op.add_column(sa.Column(
            'supported_vehicles',
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ))
        batch_op.alter_column('supported_connectors', server_default=None)
        batch_op.alter_column('supported_vehicles', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('supported_vehicles')
        batch_op.drop_column('supported_connectors')

    # ### end Alembic commands ###
