"""Initial database schema

Revision ID: af0486fa4792
Revises: 
Create Date: 2026-06-27 20:12:01.149806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0486fa4792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_users',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guest_id')
    )
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_guest_users_mobile_number'), ['mobile_number'], unique=True)
        batch_op.create_index('ix_guest_users_mobile_vehicle', ['mobile_number', 'vehicle_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_users_vehicle_number'), ['vehicle_number'], unique=False)

    op.create_table('stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price_per_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('station_name', 'city', name='uq_station_name_city')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_city'), ['city'], unique=False)
        batch_op.create_index('ix_stations_city_status', ['city', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_station_name'), ['station_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_status'), ['status'], unique=False)

    op.create_table('chargers',
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('charger_name', sa.String(length=120), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('power_kw', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Busy', 'Offline', 'Maintenance', name='charger_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('charger_id'),
    sa.UniqueConstraint('station_id', 'charger_name', name='uq_charger_station_name')
    )
    with op.batch_alter_table('chargers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chargers_connector_type'), ['connector_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chargers_station_id'), ['station_id'], unique=False)
        batch_op.create_index('ix_chargers_station_status', ['station_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chargers_status'), ['status'], unique=False)

    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('booking_status', sa.Enum('Pending', 'Confirmed', 'Completed', 'Cancelled', 'Expired', name='booking_status_enum'), nullable=False),
    sa.Column('booking_token_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.charger_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guest_id'], ['guest_users.guest_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_booking_status'), ['booking_status'], unique=False)
        batch_op.create_index('ix_bookings_charger_date_time', ['charger_id', 'booking_date', 'booking_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_charger_id'), ['charger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index('ix_bookings_guest_status', ['guest_id', 'booking_status'], unique=False)
        batch_op.create_index('ix_bookings_station_date', ['station_id', 'booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_station_id'), ['station_id'], unique=False)

    op.create_table('iot_data',
    sa.Column('iot_id', sa.Integer(), nullable=False),
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('voltage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('power', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('charger_status', sa.Enum('Available', 'Busy', 'Offline', 'Maintenance', name='charger_status_enum'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.charger_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iot_id')
    )
    with op.batch_alter_table('iot_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iot_data_charger_id'), ['charger_id'], unique=False)
        batch_op.create_index('ix_iot_data_charger_last_updated', ['charger_id', 'last_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_iot_data_charger_status'), ['charger_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_iot_data_last_updated'), ['last_updated'], unique=False)

    op.create_table('charging_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('units_consumed', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('charging_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booking_token_adjustment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charging_sessions_booking_id'), ['booking_id'], unique=True)

    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=150), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('Pending', 'Success', 'Failed', 'Refunded', name='payment_status_enum'), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_booking_id'), ['booking_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payments_booking_id'))

    op.drop_table('payments')
    with op.batch_alter_table('charging_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charging_sessions_booking_id'))

    op.drop_table('charging_sessions')
    with op.batch_alter_table('iot_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iot_data_last_updated'))
        batch_op.drop_index(batch_op.f('ix_iot_data_charger_status'))
        batch_op.drop_index('ix_iot_data_charger_last_updated')
        batch_op.drop_index(batch_op.f('ix_iot_data_charger_id'))

    op.drop_table('iot_data')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_station_id'))
        batch_op.drop_index('ix_bookings_station_date')
        batch_op.drop_index('ix_bookings_guest_status')
        batch_op.drop_index(batch_op.f('ix_bookings_guest_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_charger_id'))
        batch_op.drop_index('ix_bookings_charger_date_time')
        batch_op.drop_index(batch_op.f('ix_bookings_booking_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_date'))

    op.drop_table('bookings')
    with op.batch_alter_table('chargers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chargers_status'))
        batch_op.drop_index('ix_chargers_station_status')
        batch_op.drop_index(batch_op.f('ix_chargers_station_id'))
        batch_op.drop_index(batch_op.f('ix_chargers_connector_type'))

    op.drop_table('chargers')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_status'))
        batch_op.drop_index(batch_op.f('ix_stations_station_name'))
        batch_op.drop_index('ix_stations_city_status')
        batch_op.drop_index(batch_op.f('ix_stations_city'))

    op.drop_table('stations')
    with op.batch_alter_table('guest_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_users_vehicle_number'))
        batch_op.drop_index('ix_guest_users_mobile_vehicle')
        batch_op.drop_index(batch_op.f('ix_guest_users_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_guest_users_email'))

    op.drop_table('guest_users')
    # ### end Alembic commands ###
